#!/bin/bash

eval "python categoryper.py userid_timestamp_bookmark_url_202007_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202006_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202005_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202004_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202003_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202002_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_202001_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201912_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201911_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201910_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201909_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201908_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201907_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201906_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201905_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201904_re_ca.txt"
eval "python categoryper.py userid_timestamp_bookmark_url_201903_re_ca.txt"
