#!/bin/bash
#data.py
eval "python data.py userid_timestamp_bookmark_url_202007_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202006_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202005_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202004_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202003_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202002_re.txt"
eval "python data.py userid_timestamp_bookmark_url_202001_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201912_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201911_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201910_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201909_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201908_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201907_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201906_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201905_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201904_re.txt"
eval "python data.py userid_timestamp_bookmark_url_201903_re.txt"

##calc_time.py
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202006_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202005_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202004_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202003_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202002_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_202001_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201912_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201911_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201910_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201909_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201908_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201907_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201906_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201905_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201904_re.txt"
# eval "python calc_time.py userid_timestamp_bookmark_url_202007_re.txt userid_timestamp_bookmark_url_201903_re.txt"
